AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - '.kitchen/*'
    - 'Thorfile'
    - 'Berksfile'
    - 'Vagrantfile'
    - 'Gemfile'
    - 'Rakefile'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 60
  CountComments: false
  Enabled: true

Encoding:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

BracesAroundHashParameters:
  EnforcedStyle: false

EmptyLiteral:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

#HashSyntax:
#  EnforcedStyle: hash_rockets

Documentation:
  Enabled: false
